### DISCUSSION TITLE
Helix Configuration

### DISCUSSION THREAD

**Discussion by nyonson** [Automattic/harper#135] [Q&A] [answered]
I poked around the documentation a bit, but not sure I saw any definitive examples for Helix configuration. I have a the bare-minimum working below in my Helix `languages.toml`:

```
[language-server.harper-ls]
args = ["--stdio"]
command = "harper-ls"
```

It wasn't obvious to me that the `--stdio` flag should be used and that it must go in the separate `args` key.

With that said, any recommendations for best settings beyond that? I think I want to add some sort of de-bouncer setting since this is firing way to often as I type, but not clear to me yet the best spot to put that.

**Comment by novusnota** [comment, marked as answer]
@nyonson It is possible to use all the same settings as [shown here for Neovim](https://github.com/elijah-potter/harper/blob/master/harper-ls/README.md#configuration), but in Helix. You'll only need to wrap all the configuration options there under the `harper-ls` key in TOML dictionary.

Here's an example of how it currently works:

```toml
[language-server.harper-ls]
args = ["--stdio"]
command = "harper-ls"
# notice the key:
config = { harper-ls = { diagnosticSeverity = "error", linters = { long_sentences = false } } }
```

That config makes all the diagnostics appear as errors instead of hints (which is the default), and also disables the long sentences lint. Unfortunately, there's no debouncing or similar config option yet.
