### ISSUE TITLE
Pre-commit support

### ISSUE THREAD

**Issue by Sajjon** [Automattic/harper#130]
Would be nice with support and guide to use Harper with [`pre-commit` tool](https://pre-commit.com/) just like [`typos` CLI tool do](https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md)

**Comment by lukasmwerner** [comment]
Not sure if this helps but harper provides `harper-cli` which you can use to write a script to check all files.

This is a bit quick and dirty but works.
```bash
find . -type f -not -iwholename '*.git*' -exec harper-cli lint {} \;
```

You can install harper-cli using the following command: `cargo install --git https://github.com/elijah-potter/harper harper-cli`. I will note that harper-cli doesn't follow any dictionaries currently

**Comment by elijah-potter** [comment]
@lukasmwerner is absolutely right. I will caution that `harper-cli` currently exists primarily for testing purposes. If anyone is interested in making changes toward turning it into a more robust experience for tools like `pre-commit`, feel free to leave a comment on this issue and we can make it happen. I personally don't have time to expand scope in this way at the moment.

**Comment by jgstew** [comment]
I am curious about using harper-cli in pre-commit and/or github actions. I did get it running in github actions, but it is annoying that it can only handle a single file at a time. The single file at a time is not an issue for pre-commit though.

Example github action:

```
---
name: grammar-check

on: workflow_dispatch

jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu

      - name: install harper grammar checker
        run: cargo install --locked --git https://github.com/Automattic/harper.git --branch master --tag v0.23.0 harper-cli

      - name: run harper grammar checker
        run: harper-cli lint README.md
```

**Comment by jgstew** [comment]
pre-commit does not seem to support monorepos very well, so running harper-cli as a pre-commit hook doesn't seem to work.

I tested using harper-cli as a pre-commit hook using this `.pre-commit-hooks.yaml`

```
---
- id: harper-cli
  name: harper-cli
  description: This hook runs the harper-cli grammar checker against files
  entry: harper/harper-cli Lint
  language: rust
  pass_filenames: True
  types: [text]
```

Which then could be tested using my fork using a `.pre-commit-config.yaml` file in another repo to test with:

```
  - repo: https://github.com/jgstew/harper
    rev: 3bc8ad681de6a3c0af6df1ceca5417c82d264ff8
    hooks:
      - id: harper-cli
```

It gives the following error: 

```
error: found a virtual manifest at `(redacted)\.cache\pre-commit\repowto_rty8\Cargo.toml` instead of a package manifest
```

This is because pre-commit will only look at the Cargo.toml at the root of the repo, but really it needs to look at the one under harper-cli/Cargo.toml
