### ISSUE TITLE
Rules no longer working in Helix

### ISSUE THREAD

**Issue by bryanweatherly** [Automattic/harper#785]
After updating to 0.23, my  rules are no longer being honored in Helix.

Here is the entirety on the harper config in my `languages.toml` file:

```toml
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
diagnosticSeverity = "hint"

[language-server.harper-ls.config.harper-ls.linters]
spell_check = false
sentence_capitalization = false
```

This was working perfectly until the 0.23 update, but now I'm getting both spelling and sentence capitalization warnings.
